//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace OpenBankingApi.NSwagGenerated.v3_1_1
{
    #pragma warning disable

    // WARNING: DO NOT MANUALLY EDIT THIS FILE - regenerate_core_controllers.bat regenerates from the Swagger spec!
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IOpenBankingAccountsImplementor
    {
        /// <summary>Get Accounts</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Accounts Read</returns>
        System.Threading.Tasks.Task<OBReadAccount3> AccountsGetAsync(string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
        /// <summary>Get Accounts</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Accounts Read</returns>
        System.Threading.Tasks.Task<OBReadAccount3> AccountsGetAsync(string accountId, string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("open-banking/v3.1/aisp")]
    public partial class OpenBankingAccountsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IOpenBankingAccountsImplementor _implementation;
    
        public OpenBankingAccountsController(IOpenBankingAccountsImplementor implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get Accounts</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Accounts Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("accounts")]
        public System.Threading.Tasks.Task<OBReadAccount3> AccountsGet([Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.AccountsGetAsync(x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
        /// <summary>Get Accounts</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Accounts Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("accounts/{AccountId}")]
        public System.Threading.Tasks.Task<OBReadAccount3> AccountsGet(string accountId, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.AccountsGetAsync(accountId, x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
    }
    
    // WARNING: DO NOT MANUALLY EDIT THIS FILE - regenerate_core_controllers.bat regenerates from the Swagger spec!
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IOpenBankingBalancesImplementor
    {
        /// <summary>Get Balances</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Balances Read</returns>
        System.Threading.Tasks.Task<OBReadBalance1> BalancesGetAsync(string accountId, string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
        /// <summary>Get Balances</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Balances Read</returns>
        System.Threading.Tasks.Task<OBReadBalance1> BalancesGetAsync(string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("open-banking/v3.1/aisp")]
    public partial class OpenBankingBalancesController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IOpenBankingBalancesImplementor _implementation;
    
        public OpenBankingBalancesController(IOpenBankingBalancesImplementor implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get Balances</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Balances Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("accounts/{AccountId}/balances")]
        public System.Threading.Tasks.Task<OBReadBalance1> BalancesGet(string accountId, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.BalancesGetAsync(accountId, x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
        /// <summary>Get Balances</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Balances Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("balances")]
        public System.Threading.Tasks.Task<OBReadBalance1> BalancesGet([Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.BalancesGetAsync(x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
    }
    
    // WARNING: DO NOT MANUALLY EDIT THIS FILE - regenerate_core_controllers.bat regenerates from the Swagger spec!
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IOpenBankingProductsImplementor
    {
        /// <summary>Get Products</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Products Read</returns>
        System.Threading.Tasks.Task<OBReadProduct2> ProductAsync(string accountId, string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
        /// <summary>Get Products</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Products Read</returns>
        System.Threading.Tasks.Task<OBReadProduct2> ProductsAsync(string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, string x_customer_user_agent = null);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("open-banking/v3.1/aisp")]
    public partial class OpenBankingProductsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IOpenBankingProductsImplementor _implementation;
    
        public OpenBankingProductsController(IOpenBankingProductsImplementor implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get Products</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Products Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("accounts/{AccountId}/product")]
        public System.Threading.Tasks.Task<OBReadProduct2> Product(string accountId, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.ProductAsync(accountId, x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
        /// <summary>Get Products</summary>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Products Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("products")]
        public System.Threading.Tasks.Task<OBReadProduct2> Products([Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.ProductsAsync(x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, x_customer_user_agent);
        }
    
    }
    
    // WARNING: DO NOT MANUALLY EDIT THIS FILE - regenerate_core_controllers.bat regenerates from the Swagger spec!
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IOpenBankingTransactionsImplementor
    {
        /// <summary>Get Transactions</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="fromBookingDateTime">The UTC ISO 8601 Date Time to filter transactions FROM
        /// NB Time component is optional - set to 00:00:00 for just Date.
        /// If the Date Time contains a timezone, the ASPSP must ignore the timezone component.</param>
        /// <param name="toBookingDateTime">The UTC ISO 8601 Date Time to filter transactions TO
        /// NB Time component is optional - set to 00:00:00 for just Date.
        /// If the Date Time contains a timezone, the ASPSP must ignore the timezone component.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Transactions Read</returns>
        System.Threading.Tasks.Task<OBReadTransaction5> TransactionsAsync(string accountId, string x_fapi_financial_id, string authorization, string x_fapi_customer_last_logged_time = null, string x_fapi_customer_ip_address = null, string x_fapi_interaction_id = null, System.DateTimeOffset? fromBookingDateTime = null, System.DateTimeOffset? toBookingDateTime = null, string x_customer_user_agent = null);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.2.5.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v12.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("open-banking/v3.1/aisp")]
    public partial class OpenBankingTransactionsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IOpenBankingTransactionsImplementor _implementation;
    
        public OpenBankingTransactionsController(IOpenBankingTransactionsImplementor implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get Transactions</summary>
        /// <param name="accountId">AccountId</param>
        /// <param name="x_fapi_financial_id">The unique id of the ASPSP to which the request is issued. The unique id will be issued by OB.</param>
        /// <param name="authorization">An Authorisation Token as per https://tools.ietf.org/html/rfc6750</param>
        /// <param name="x_fapi_customer_last_logged_time">The time when the PSU last logged in with the TPP. 
        /// All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: 
        /// Sun, 10 Sep 2017 19:43:31 UTC</param>
        /// <param name="x_fapi_customer_ip_address">The PSU's IP address if the PSU is currently logged in with the TPP.</param>
        /// <param name="x_fapi_interaction_id">An RFC4122 UID used as a correlation id.</param>
        /// <param name="fromBookingDateTime">The UTC ISO 8601 Date Time to filter transactions FROM
        /// NB Time component is optional - set to 00:00:00 for just Date.
        /// If the Date Time contains a timezone, the ASPSP must ignore the timezone component.</param>
        /// <param name="toBookingDateTime">The UTC ISO 8601 Date Time to filter transactions TO
        /// NB Time component is optional - set to 00:00:00 for just Date.
        /// If the Date Time contains a timezone, the ASPSP must ignore the timezone component.</param>
        /// <param name="x_customer_user_agent">Indicates the user-agent that the PSU is using.</param>
        /// <returns>Transactions Read</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("accounts/{AccountId}/transactions")]
        public System.Threading.Tasks.Task<OBReadTransaction5> Transactions(string accountId, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-financial-id")] string x_fapi_financial_id, [Microsoft.AspNetCore.Mvc.FromHeader] string authorization, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-last-logged-time")] string x_fapi_customer_last_logged_time = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-customer-ip-address")] string x_fapi_customer_ip_address = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-fapi-interaction-id")] string x_fapi_interaction_id = null, System.DateTimeOffset? fromBookingDateTime = null, System.DateTimeOffset? toBookingDateTime = null, [Microsoft.AspNetCore.Mvc.FromHeader(Name = "x-customer-user-agent")] string x_customer_user_agent = null)
        {
            return _implementation.TransactionsAsync(accountId, x_fapi_financial_id, authorization, x_fapi_customer_last_logged_time, x_fapi_customer_ip_address, x_fapi_interaction_id, fromBookingDateTime, toBookingDateTime, x_customer_user_agent);
        }
    
    }

    

    #pragma warning restore
}